#!/usr/bin/env npx ts-node
/**
 * Skill Pack Builder
 *
 * Builds a distributable skill pack from all n8n skills.
 * Creates both a single-file bundle and a zip archive.
 *
 * Run with: npx ts-node scripts/build-skill-pack.ts
 *
 * Options:
 *   --output <dir>  Output directory (default: ./skill-pack)
 *   --zip           Create zip archive
 *   --validate      Run validation before building (default: true)
 */

import * as fs from 'fs';
import * as path from 'path';

interface SkillInfo {
  id: string;
  name: string;
  description: string;
  file: string;
  size: number;
}

interface PackManifest {
  name: string;
  version: string;
  description: string;
  generatedAt: string;
  n8nVersionTested: string;
  skills: SkillInfo[];
  totalSize: number;
  checksum: string;
}

const SKILLS_DIR = path.join(__dirname, '..', '.claude', 'skills');
const DEFAULT_OUTPUT = path.join(__dirname, '..', 'skill-pack');

// Parse command line arguments
const args = process.argv.slice(2);
const outputDir = args.includes('--output')
  ? args[args.indexOf('--output') + 1]
  : DEFAULT_OUTPUT;
const createZip = args.includes('--zip');
const skipValidation = args.includes('--no-validate');

function extractSkillInfo(skillDir: string): SkillInfo | null {
  const skillPath = path.join(SKILLS_DIR, skillDir);
  const skillFile = path.join(skillPath, 'SKILL.md');

  if (!fs.existsSync(skillFile)) {
    console.error(`  SKIP: ${skillDir} (no SKILL.md)`);
    return null;
  }

  const content = fs.readFileSync(skillFile, 'utf-8');
  const stats = fs.statSync(skillFile);

  // Extract title
  const titleMatch = content.match(/^# (.+)$/m);
  const title = titleMatch ? titleMatch[1] : skillDir;

  // Extract description
  const descMatch = content.match(/^> \*\*(.+?)\*\*/m);
  const description = descMatch ? descMatch[1] : 'No description';

  return {
    id: skillDir,
    name: title,
    description: description,
    file: `${skillDir}.md`,
    size: stats.size,
  };
}

function generateChecksum(content: string): string {
  // Simple checksum (in production, use crypto.createHash)
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  return Math.abs(hash).toString(16).padStart(8, '0');
}

function buildSingleFileBundle(skills: SkillInfo[]): string {
  let bundle = `# n8n Skills Pro - Complete Pack
> **Comprehensive n8n workflow automation skills for AI assistants**

Generated: ${new Date().toISOString()}
Skills: ${skills.length}

---

## Table of Contents

`;

  // Add TOC
  for (const skill of skills) {
    bundle += `- [${skill.name}](#${skill.id})\n`;
  }

  bundle += '\n---\n\n';

  // Add each skill
  for (const skill of skills) {
    const skillPath = path.join(SKILLS_DIR, skill.id, 'SKILL.md');
    const content = fs.readFileSync(skillPath, 'utf-8');

    bundle += `<a id="${skill.id}"></a>\n\n`;
    bundle += content;
    bundle += '\n\n---\n\n';
  }

  // Add footer
  bundle += `
## About This Pack

This skill pack was generated by n8n-skills-pro.

- Repository: https://github.com/Chol369/n8n-skills-pro
- Author: Atak Chol (@Chol369)
- License: MIT

### How to Use

1. **Claude Code CLI**: Place in \`.claude/skills/\` directory
2. **Claude.ai**: Paste into project knowledge
3. **Claude Desktop**: Add to project instructions

### Updates

This pack is auto-generated. Check the repository for the latest version.

---

*Generated with n8n-skills-pro build-skill-pack.ts*
`;

  return bundle;
}

function buildClaudeDesktopFormat(skills: SkillInfo[]): string {
  let content = `# n8n Workflow Automation Skills

> Use these skills to build, validate, and deploy n8n workflows.

## Available Skills

`;

  for (const skill of skills) {
    content += `### ${skill.name}\n${skill.description}\n\n`;
  }

  content += `---

## Quick Reference

### MCP Tools for n8n

| Tool | Purpose |
|------|---------|
| \`search_nodes\` | Find nodes by keyword |
| \`get_node\` | Get node configuration |
| \`validate_node\` | Check node config |
| \`validate_workflow\` | Validate full workflow |
| \`n8n_create_workflow\` | Create workflow |
| \`n8n_test_workflow\` | Execute workflow |

### Node Type Formats

| Context | Format | Example |
|---------|--------|---------|
| MCP search/get | \`nodes-base.X\` | \`nodes-base.slack\` |
| Workflow JSON | \`n8n-nodes-base.X\` | \`n8n-nodes-base.slack\` |
| AI nodes (MCP) | \`nodes-langchain.X\` | \`nodes-langchain.agent\` |
| AI nodes (JSON) | \`@n8n/n8n-nodes-langchain.X\` | \`@n8n/n8n-nodes-langchain.agent\` |

---

*For complete documentation, see the full skill pack.*
`;

  return content;
}

async function runValidation(): Promise<boolean> {
  console.log('Running skill validation...');

  // Simple validation - check all SKILL.md files exist
  const skills = fs.readdirSync(SKILLS_DIR)
    .filter(d => fs.statSync(path.join(SKILLS_DIR, d)).isDirectory())
    .sort();

  let valid = true;
  for (const skill of skills) {
    const skillFile = path.join(SKILLS_DIR, skill, 'SKILL.md');
    if (!fs.existsSync(skillFile)) {
      console.error(`  ERROR: ${skill}/SKILL.md not found`);
      valid = false;
    }
  }

  return valid;
}

async function createZipArchive(sourceDir: string, outputPath: string): Promise<void> {
  // Note: For actual zip creation, you'd use 'archiver' package
  // This is a placeholder that creates a manifest instead
  console.log(`  ZIP: Archive creation requires 'archiver' package`);
  console.log(`  Creating manifest file instead...`);

  const manifest = {
    archive: outputPath,
    created: new Date().toISOString(),
    files: fs.readdirSync(sourceDir),
    note: 'Install archiver package for actual zip creation: npm install archiver',
  };

  fs.writeFileSync(
    path.join(sourceDir, 'ARCHIVE_MANIFEST.json'),
    JSON.stringify(manifest, null, 2)
  );
}

async function buildSkillPack(): Promise<void> {
  console.log('='.repeat(60));
  console.log('n8n Skills Pro - Pack Builder');
  console.log('='.repeat(60));
  console.log();

  // Validate if requested
  if (!skipValidation) {
    const isValid = await runValidation();
    if (!isValid) {
      console.error('\nValidation failed. Fix errors before building.');
      process.exit(1);
    }
    console.log('  Validation passed\n');
  }

  // Create output directory
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  console.log(`Output directory: ${outputDir}`);
  console.log();

  // Gather skill information
  console.log('Gathering skills...');
  const skillDirs = fs.readdirSync(SKILLS_DIR)
    .filter(d => fs.statSync(path.join(SKILLS_DIR, d)).isDirectory())
    .sort();

  const skills: SkillInfo[] = [];
  for (const dir of skillDirs) {
    const info = extractSkillInfo(dir);
    if (info) {
      skills.push(info);
      console.log(`  + ${info.id}: ${info.name}`);
    }
  }

  console.log(`\nFound ${skills.length} skills\n`);

  // Build single-file bundle
  console.log('Building single-file bundle...');
  const bundle = buildSingleFileBundle(skills);
  const bundlePath = path.join(outputDir, 'n8n-skills-complete.md');
  fs.writeFileSync(bundlePath, bundle);
  console.log(`  Created: ${bundlePath}`);

  // Build Claude Desktop format
  console.log('Building Claude Desktop format...');
  const desktopContent = buildClaudeDesktopFormat(skills);
  const desktopPath = path.join(outputDir, 'n8n-skills-quick-reference.md');
  fs.writeFileSync(desktopPath, desktopContent);
  console.log(`  Created: ${desktopPath}`);

  // Copy individual skill files
  console.log('Copying individual skills...');
  const individualDir = path.join(outputDir, 'individual');
  if (!fs.existsSync(individualDir)) {
    fs.mkdirSync(individualDir, { recursive: true });
  }

  for (const skill of skills) {
    const srcPath = path.join(SKILLS_DIR, skill.id, 'SKILL.md');
    const destPath = path.join(individualDir, `${skill.id}.md`);
    fs.copyFileSync(srcPath, destPath);
  }
  console.log(`  Copied ${skills.length} files to ${individualDir}`);

  // Generate manifest
  console.log('Generating manifest...');
  const totalSize = skills.reduce((sum, s) => sum + s.size, 0);
  const manifest: PackManifest = {
    name: 'n8n-skills-pro',
    version: '1.0.0',
    description: 'Comprehensive n8n workflow automation skills for AI assistants',
    generatedAt: new Date().toISOString(),
    n8nVersionTested: '2.1.x',
    skills: skills,
    totalSize: totalSize,
    checksum: generateChecksum(bundle),
  };

  const manifestPath = path.join(outputDir, 'manifest.json');
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  console.log(`  Created: ${manifestPath}`);

  // Create zip if requested
  if (createZip) {
    console.log('Creating zip archive...');
    await createZipArchive(outputDir, path.join(outputDir, 'n8n-skills-pro.zip'));
  }

  // Summary
  console.log();
  console.log('='.repeat(60));
  console.log('Build Complete!');
  console.log('='.repeat(60));
  console.log();
  console.log('Generated files:');
  console.log(`  - ${bundlePath} (single file, all skills)`);
  console.log(`  - ${desktopPath} (quick reference)`);
  console.log(`  - ${individualDir}/ (${skills.length} individual files)`);
  console.log(`  - ${manifestPath} (build manifest)`);
  console.log();
  console.log(`Total size: ${(totalSize / 1024).toFixed(1)} KB`);
  console.log(`Checksum: ${manifest.checksum}`);
  console.log();
  console.log('Usage:');
  console.log('  Claude Code: Copy individual/ contents to .claude/skills/');
  console.log('  Claude.ai: Upload n8n-skills-complete.md to project knowledge');
  console.log('  Claude Desktop: Use n8n-skills-quick-reference.md');
}

// Run builder
buildSkillPack().catch(console.error);
